### ISSUE TITLE
Mismatch between Jupyter notebooks and gh-pages

### ISSUE THREAD

**Issue by bpstewar** [worldbank/GOSTurban#22]
My most recent commit built successfully, but the gh-pages do not reflect the updated pages:

- Successful commit - https://github.com/worldbank/GOSTurban/actions/runs/8086627097
- Tutorial to be included in gh-pages - https://github.com/worldbank/GOSTurban/blob/main/notebooks/Tutorials/UrbanAreas_tutorials.ipynb
- Gh-page that has not been updated - https://worldbank.github.io/GOSTurban/notebooks/Tutorials/UrbanAreas_tutorials.html

**Comment by g4brielvs** [comment]
@elbeejay Could you please investigate and fix this issue?
